#default browser: chrome
#default environment: test1

browsers:
#  chrome: CHROME
#  firefox: FIREFOX
#  ie: IE
#  edge: EDGE

environment:
  test1:
    envName: test1
    webUrl: http://www.automationpractice.pl/index.php
    wait: 15
    blousesCategoryTitle: "BLOUSES "
#    active: true

  test2:
    envName: test2
    webUrl: http://146.59.32.4/
    wait: 10
    title: TesterSii
    login: userTest2
    password: passwordTest2
#    active: false

  prod:
    envName: prod
    webUrl: https://www.filmweb.pl/
    wait: 10
    title: Filmweb - filmy takie jak Ty!
    login: userProd
    password: passwordProd
#    active: false

dataBase:
  postgres:
    dbName: dbPostgres
    host: 18.23.55.80
    user: postgresUser
    dbPassword: postgresPassword
#    active: true

  mySql:
    dbName: dbMySql
    host: 19.55.23.70
    user: mySqlUser
    dbPassword: mySqlPassword
#    active: true












